### ISSUE TITLE
Extract and expose fuction for WAI request -> Honeybadger request

### ISSUE THREAD

**Issue by emhoracek** [tfausak/ratel-wai#3]
The WAI middleware is working great, but once in a while an exception comes up and I want to handle it instead of letting it bubble up to the middleware. In this case, I'd still like to use ratel's `notify` to notify Honeybadger, but now I need to put together the `Payload` myself. It would be handy to have a `toRequest` function for WAI requests, the same way there's a `toError` for exceptions.

I can go ahead and make a PR for this if you don't mind?

**Comment by tfausak** [comment]
Great idea! Your PR (#4) looks good. I'd be happy to merge it and cut a new release.
